SELECT SECTOR_ID,SECTOR_NAME,ENODEB_NAME,LONGITUDE,LATITUDE,PCI as "Physical Cell Identity",AZIMUTH,HEIGHT
FROM user58db.`1.tbcell`
WHERE LONGITUDE BETWEEN 100 AND 120 
AND CITY = "sanxia"
AND LATITUDE BETWEEN 20 AND 40
AND PCI BETWEEN 0 AND 200
AND VENDOR is not null
ORDER BY LONGITUDE DESC,LATITUDE DESC, EARFCN DESC;