SELECT SECTOR_NAME
FROM user58db.`1.tbcell`
WHERE (SECTOR_NAME LIKE "A池%"
	OR SECTOR_NAME LIKE "高铁%"
    OR SECTOR_NAME LIKE "%医院%"
    OR SECTOR_NAME LIKE "%实验高中%")
    AND NOT SECTOR_NAME LIKE "%-1";