SELECT DISTINCT T1.ENODEBID, T1.LONGITUDE, T1.LATITUDE, T2.LONGITUDE, T2.LATITUDE
FROM user60db.`1.tbcell` as T1, user60db.`1.tbcell` as T2
WHERE T1.ENODEBID = T2.ENODEBID and T1.LONGITUDE != T2.LONGITUDE and T1.LATITUDE != T2.LATITUDE
    